clear
set more off

use "/Users/caw6/Desktop/UrbanizationCauseConsequence/data/cointegratedGDPPerCapLCU.dta"

// booleans to indicate whether we fail to reject the null at the 5% confidence level
gen unitRoot = 0

// Critical values: -3.0, -3.6 (trend), -1.95 (nocons)
scalar criticalValue = -4
local var "PctPopUrban"
local testSpec "trend"
local test "B"

levels(Country), local(countries)
//putexcel set "/Users/caw6/Desktop/UrbanizationCauseConsequence/test-results/UnitRoots/GDPPerCap_results.xlsx", modify sheet(`var')

/*
putexcel A1 = "Country"
local i "2"
foreach country of local countries {
	putexcel A`i' = ("`country'")
	local ++i
}*/

//putexcel `test'1 = "`testSpec'"
local j "2"
foreach country of local countries {
	// Null:		variable contains a unit root -> nonstationary
	// Alternative	variable generated by a stationary process
	
	dfuller `var' if Country == "`country'" & Year >= 1975, `testSpec'
	replace unitRoot = 1 if r(Zt) >= criticalValue & Country == "`country'"
	
	//putexcel `test'`j' = (r(Zt))
	local ++j
}
tab Country if unitRoot == 1
/*
xtunitroot ips `var' if unitRoot == 1
xtunitroot ips `var' if unitRoot == 1, trend
xtunitroot ips `var' if unitRoot == 1, trend lags(aic 6)
xtunitroot ips `var' if unitRoot == 1, demean
xtunitroot ips `var' if unitRoot == 1, demean lags(aic 6)
xtunitroot ips `var' if unitRoot == 1, lags(aic 8)
*/

xtunitroot ips `var' if unitRoot == 1 & Year >= 1975
xtunitroot ips `var' if unitRoot == 1 & Year >= 1975, trend
xtunitroot ips `var' if unitRoot == 1 & Year >= 1975, trend lags(aic 6)
xtunitroot ips `var' if unitRoot == 1 & Year >= 1975, demean
xtunitroot ips `var' if unitRoot == 1 & Year >= 1975, demean lags(aic 6)
xtunitroot ips `var' if unitRoot == 1 & Year >= 1975, lags(aic 8)

/*
xtunitroot ips `var' if Year >= 1993, demean
xtunitroot llc `var' if Year >= 1993, lags(aic 4)
xtunitroot llc `var' if Year >= 1993, trend
*/

// Drop failures and save the data
/*
// drop countries that fail either test
keep if unitRootGDP == 1 & unitRootUrban == 1
drop unitRootGDP
drop unitRootUrban


save "/Users/caw6/Desktop/UrbanizationCauseConsequence/data/unitroots.dta", replace
*/
