clear
set more off

use "/Users/caw6/Desktop/UrbanizationCauseConsequence/WDIUrbanDev-clean.dta"

// booleans to indicate whether we fail to reject the null at the 5% confidence level
generate byte unitRootGDP = 0
generate byte unitRootUrban = 0

scalar criticalValue = -3.6
local testSpec "lags(2)"
// local test "P"

levels(Country), local(countries)

/*
putexcel set "/Users/caw6/Desktop/UrbanizationCauseConsequence/Urban_results.xlsx", modify
putexcel A1 = "Country"
local i "2"
foreach country of local countries {
	putexcel A`i' = ("`country'")
	local ++i
}
putexcel `test'1 = "`testSpec'"
local j "2"
*/

foreach country of local countries {
	// Null:		variable contains a unit root -> nonstationary
	// Alternative	variable generated by a stationary process
	
	quietly dfuller GDPRealUSD if Country == "`country'", `testSpec'
	replace unitRootGDP = 1 if r(Zt) >= criticalValue & Country == "`country'"
	
	quietly dfuller PctPopUrban if Country == "`country'", `testSpec'
	replace unitRootUrban = 1 if r(Zt) >= criticalValue & Country == "`country'"
	
	// putexcel `test'`j' = (r(Zt))
	// local ++j
}


// drop countries that fail either test
keep if unitRootGDP == 1 & unitRootUrban == 1
drop unitRootGDP
drop unitRootUrban


save "/Users/caw6/Desktop/UrbanizationCauseConsequence/unitroots.dta", replace
